server:
  port: 8081
  session:
    timeout: 600
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://118.24.109.67/zwsdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
authentication:
 core:
    app:
       token:
          store-type: redis
    client:
         password-token-url: http://localhost:8080/oauth/token
security:
  oauth2:
    client:
      client-id: zws
      client-secret: zws













