server:
  port: 8080
spring:
  datasource:
    username: root
    password: passW0rd
    url: jdbc:mysql://192.168.1.151/crowd_sourcing?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  #redis:
   # host: 192.168.1.154
    #port: 6379
secur=ity:
   core:
      browser:
        login-type: JSON
authentication:
  core:
    social:
       filterProcessesUrl: /qqLogin
       wx:
         app-id: wxd99431bbff8305a0
         app-secret: 60f78681d063590a469f1b297feff3c4
         provider-id: weixin








