server:
  port: 8021
  context-path: /client1
security:
  oauth2:
    client:
      client-id: zws-client1
      client-secret: secret
      access-token-uri: http://127.0.0.1:8020/server/oauth/token
      user-authorization-uri: http://127.0.0.1:8020/server/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8020/server/oauth/token_key