spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zengwensheng/config
          username: 2848392861@qq.com
          basedir: /Users/zws/config/basedir
          password: 2848392861zws
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/ # 多个以逗号隔开，eureka即是服务端，也是客户端